-- ============================================================================
-- JS.ACADEMY — Supabase Database Schema
-- Run this script in the Supabase SQL Editor (https://database.supabase.com)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. CLEANUP (Optional - uncomment if you want to start fresh)
-- ----------------------------------------------------------------------------
-- DROP TABLE IF EXISTS public.replies CASCADE;
-- DROP TABLE IF EXISTS public.doubts CASCADE;
-- DROP TABLE IF EXISTS public.certificates CASCADE;
-- DROP TABLE IF EXISTS public.profiles CASCADE;

-- ----------------------------------------------------------------------------
-- 2. CREATE TABLES
-- ----------------------------------------------------------------------------

-- A. Profiles Table (Linked to Supabase Auth users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT NOT NULL,
    xp INTEGER NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 1,
    unlocked_modules TEXT[] NOT NULL DEFAULT '{}'::text[],
    completed_modules TEXT[] NOT NULL DEFAULT '{}'::text[],
    badges TEXT[] NOT NULL DEFAULT '{}'::text[],
    battle_wins INTEGER NOT NULL DEFAULT 0,
    battle_losses INTEGER NOT NULL DEFAULT 0,
    battle_games_played INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- B. Certificates Table
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    module_id TEXT NOT NULL,
    module_title TEXT NOT NULL,
    date TEXT NOT NULL,
    verification_code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- C. Doubts Table (Q&A Forum Questions)
CREATE TABLE IF NOT EXISTS public.doubts (
    id TEXT PRIMARY KEY, -- Client-generated unique ID
    module_id TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    author TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- D. Replies Table (Q&A Forum Answers)
CREATE TABLE IF NOT EXISTS public.replies (
    id TEXT PRIMARY KEY, -- Client-generated unique ID
    doubt_id TEXT NOT NULL REFERENCES public.doubts(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    author TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 3. ENABLE ROW LEVEL SECURITY (RLS)
-- ----------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doubts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.replies ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- 4. CREATE RLS POLICIES
-- ----------------------------------------------------------------------------

-- A. Profiles Policies
-- Users can view any profile (necessary for leaderboards/battles)
CREATE POLICY "Allow public read access to profiles"
    ON public.profiles FOR SELECT
    USING (true);

-- Users can insert their own profile on registration
-- Note: Set to true because user session might not be fully active on client during signup/email confirmation,
-- but database integrity is still enforced via profiles primary key & auth.users foreign key.
CREATE POLICY "Allow users to insert their own profile"
    ON public.profiles FOR INSERT
    WITH CHECK (true);

-- Users can update their own profile data (XP, level, modules...)
CREATE POLICY "Allow users to update their own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

-- B. Certificates Policies
-- Users can only view their own certificates
CREATE POLICY "Allow users to read their own certificates"
    ON public.certificates FOR SELECT
    USING (auth.uid() = user_id);

-- Users can insert certificates for themselves
CREATE POLICY "Allow users to insert their own certificates"
    ON public.certificates FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- C. Doubts Policies
-- Anyone (even unauthenticated guests) can read forum doubts
CREATE POLICY "Allow anyone to read doubts"
    ON public.doubts FOR SELECT
    USING (true);

-- Authenticated users can post doubts
CREATE POLICY "Allow authenticated users to insert doubts"
    ON public.doubts FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

-- D. Replies Policies
-- Anyone can read replies to forum doubts
CREATE POLICY "Allow anyone to read replies"
    ON public.replies FOR SELECT
    USING (true);

-- Authenticated users can reply to doubts
CREATE POLICY "Allow authenticated users to insert replies"
    ON public.replies FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);
